### ISSUE TITLE
Lovely patch for G.GAME.pack_size matches unintended lines

### ISSUE THREAD

**Issue by larswijn** [DigitalDetective47/strange-pencil#5]
One of your [lovely patches](https://github.com/DigitalDetective47/strange-pencil/blob/master/lovely.toml#L7) modifies the value of `G.GAME.pack_size`. 

This pattern unfortunately not only matches in `Card:open` (the presumed function you're trying to patch) but also:
- `Card:redeem`: the voucher redeem function. While this is no immediate issue, this does not seem intended
- `Card:start_materialize`: the card appear function. In short, this causes crashes for any mod that reads `G.GAME.pack_size` during booster pack opening (e.g. Betmma's, CardSleeves)

Could be fixed by choosing a different line for the lovely pattern to match, or turning it into e.g. a hook instead of lovely patch.

**Comment by DigitalDetective47** [comment]
fixed
